rover/roboclaw.py

I believe these functions should have been private due to the comment preceding them and due to the fact that they are only used locally. There is another section in the code for public functions, so perhaps they were originally intended to be public but I doubt that due the naming scheme and their utility. (See issue #3 which I created earlier)
_I did not run the code since I did not actually built the rover (..yet?)_

prefix private methods

---

README.md

Per issue #9 :
```Add a CONTRIBUTING.md - helps promote best practices for working on an issue or submitting a PR, sometimes occompanied by a code of conduct. (This one's also still on my backlog of things to do)```
NASA has a website with contributing info (https://code.nasa.gov/#/guide), but I'm not sure if it applies here given that this is a caltech project at heart. @asasine What do you think?

Simple contributing guide added to README

---

Arduino/OsrScreen.cpp
Arduino/OsrScreen.h
README.md

- Updated instructions to include steps for installing the required Adafruit libraries
- Fixed some incorrect steps regarding checking out the git repository, especially as related to subdirectories
- Clarified steps for including and building Arduino libraries
- Updated the OsrScreen.cpp and OsrScreen.h files to reference the Adafruit libraries in the paths that are used by the Arduino library manager when it installs the libraries.

Fixes for #23 and #24

---

ROS/osr/scripts/roboclaw_wrapper.py

Not sure why this was hardcoded as the rosparam line was commented out right above it. Giving users an indication of the existence of this rosparam in the launch file but then defaulting to the hardcoded value is a big potential source of errors. This change doesn't affect functionality in any way.
None

Use the ROS param iso hardcoded value in roboclaw_wrapper

---

ROS/osr/package.xml

It's good practice to track dependencies in package.xml. That way installation can be simplified to [rosdep install](http://wiki.ros.org/rosdep) or even releasing the package to `apt` in the future.
None

Add missing python-serial dependency to package.xml for future rosdep/apt install

---

ROS/osr/src/roboclaw_wrapper.py
ROS/osr/src/rover.py
ROS/osr_bringup/config/roboclaw_params.yaml

This change was hastily implemented and merged without review (by me). Reverts nasa-jpl/osr-rover-code#86

Revert "Updated drive code to use duties rather than (psuedo) qpps"

---

README.md
ROS/osr/CMakeLists.txt
ROS/osr/package.xml
ROS/osr/src/joystick.py
ROS/osr/src/rover.py
ROS/osr_bringup/launch/osr.launch
ROS/osr_msgs/CMakeLists.txt
ROS/osr_msgs/msg/Joystick.msg

Instead of write our own joy to twist node, we can just use an existing one, written in C++, tested, easily modifiable for different controller types ( close #13 ): [teleop_twist_joy](http://wiki.ros.org/teleop_twist_joy)
Folks who don't have that installed yet should run
```
rosdep install --from-paths src --ignore-src
```
in their catkin workspace after updating to this commit or to just install this package only via `sudo apt install ros-$ROSDISTRO-teleop-twist-joy`

Use teleop_twist_joy instead of joystick.py

---

ROS/osr/CMakeLists.txt
ROS/osr/src/joystick.py
ROS/osr/src/rover.py
ROS/osr_msgs/CMakeLists.txt
ROS/osr_msgs/msg/Joystick.msg

Close #45, which means using `geometry_msgs/Twist` instead of the custom `Joystick` message, which is deleted.  This means any common control node can move the robot, including the widely used [teleop_twist_keyboard](http://wiki.ros.org/teleop_twist_keyboard).
Leaving overhauling the rest of the code in joystick.py for a future PR.
I also scaled the velocity in both the drive and corner motors to be to the third power of the joystick movements. This means the steering is less aggressive and acceleration is slower.

Use Twist in joystick.py, make steering less aggressive

---

ROS/osr/src/roboclaw_wrapper.py

Small fix. Unlike sending duty commands, this requires properly tuned velocity control on the roboclaws, otherwise the wheels will start up at different speeds and put stress on the system or slip.

Send velocity to roboclaws instead of duty cycle

---

.gitignore
README.md
ROS/osr_bringup/launch/osr.launch

Force users to at least create a custom config file so folks can easily switch between branches and check out other users code without running the wrong settings on their rover. The modified parameters simply overwrite the default settings if they exist.
in osr_bringup/config, `touch physical_properties_mod.yaml roboclaw_params_mod.yaml` or `cp` the default yaml files. 
Add or modify the lines in the `_mod.yaml` files so that they sit in the same namespace as the default files. For example, I want to overwrite the default absolute encoder `ticks_per_rev`, then in `roboclaw_params.yaml`, I add:
```
roboclaw_mapping:
corner_left_front:
ticks_per_rev: 1732
corner_left_back:
ticks_per_rev: 1714
corner_right_back:
ticks_per_rev: 1750
corner_right_front:
ticks_per_rev: 1756
```
You can also …

Custom configs

---

ROS/osr/src/roboclaw_wrapper.py
ROS/osr_bringup/config/physical_properties.yaml

* set the drive and corner motor acceleration using a ROS param, in `physical_properties_mod.yaml`
* change the default from max to half the max acceleration. That will let the rover slow down and speed up slower, increasing gearbox lifetime. Also fix the max to be 2**15-1 iso `655359`. See [roboclaw blog](https://resources.basicmicro.com/understanding-acceleration-and-deceleration-values/) for details.
None

motor acceleration parameters

---

ROS/osr/src/roboclaw_wrapper.py
ROS/osr_msgs/msg/Status.msg

See #97 and #58 
also closes #102 
This also checks for errors more continuously (this previously only happened on startup) and logs them to console in addition to adding them to the message.

divide status values by 10, change message definitions

---

ROS/osr/src/roboclaw_wrapper.py
ROS/osr_bringup/config/physical_properties.yaml
ROS/osr_msgs/msg/Status.msg

close #104 
When the joystick suddenly disconnects at the peak of a command or something else disconnects, then the rover should stop driving after a few seconds of not receiving a command. 
Ideally this should be done at the roboclaw level, but not sure if this is possible.

Timeout on velocity commands

---

setup/rpi.md

Upon debugging with new people setting up the rpi with Ubuntu 18.04, found we need an additional command to disable the serial-getty@ttyS0.service, so it won't stomp all over serial comms with the roboclaws.

Adding extra mask command for fully STFU'ing serial-getty@ttyS0.service

---

ROS/osr_bringup/config/physical_properties.yaml
ROS/osr_bringup/config/roboclaw_params.yaml
ROS/osr_bringup/launch/osr.launch

Now that the open-source-rover repo has GoBilda as the default drive motors, the code must follow too to. For those with different motors, make use of the `_mod.yaml` files as described in the README to update the file to reflect your motors if they corresponded to the defaults.

Update defaults to GoBilda motors

---

ROS/osr/src/roboclaw_wrapper.py

Made the rover truly idle when it's supposed to be idle
Now we command the wheels to fully stop when a command hasn't been received for a little bit. This consumes less current, and avoids the chattering noise that was present when idle before.

Make rover full stop the wheels when idle

---

.gitignore
ROS/osr_bringup/launch/.gitignore
init_scripts/LaunchOSR.sh
init_scripts/launch_osr.sh
init_scripts/osr_paths.sh
init_scripts/osr_startup.service
setup/rover_bringup.md

Made the launch script more robust
- using symbolic links now so that updates get captured in the systemd service
- allow usage of custom osr_mod.launch file if you want to disclude e.g. the led screen node

Robustify launch script

---

ROS/osr/src/rover.py

This overwrote the covariance set in in `__init__()`

Remove spurious covariance reset

---

ROS/osr/src/rover.py

The original covariance values are for linear and angular velocities, but they were added to the pose covariance matrix rather than twist

Move pose covariance values to twist

---

Arduino/OsrScreen.cpp
Arduino/OsrScreen.h

Sorted and Grouped RGBmatrixPanel Eyes, Cheeks, and Mouths. Added 'shocked_face' (along with child functions 'open_mouth' and 'shocked_eyes'). This added expression can be used / triggered by error events, Accelerometers, etc.
The main purpose of this extension was to explore the addition of faces, since this seems like an easy position for first-time open source contributors to enter with little cost overhead.
In the future, I intent to create a README.md and split out the code into sub-files so that it will be easier for first time open source contributors to get the handle on this.
Educationally, I could see this being an incredible first step for many students whose families / schools don't have the financial resources to afford the whole $2500 rover.

Addition of Facial Expression: SHOCK

---

ROS/osr_bringup/config/roboclaw_params.yaml

Closes [#open-source-rover/447](https://github.com/nasa-jpl/open-source-rover/issues/447)

Flip default address for drive_right_back and drive_right_front

---

ROS/osr_control/osr_control/roboclaw_wrapper.py
ROS/osr_control/osr_control/rover.py

This fixes the error 
```
clpy.exceptions.InvalidParameterTypeException: Trying to set parameter 'rover_dimensions.d1' to '0.177' of type 'DOUBLE', expecting type 'NOT_SET'
```
which is a phenomenon that occurs on newer versions of ROS 2 (not on foxy/galactic).
@abust005

Replace None's with parameter types

---

ROS/osr_bringup/launch/osr_launch.py

If one of these nodes dies at launch or because of a one-time error, the rover stops working. Respawning is a solution

Respawn essential nodes

---

ROS/osr_bringup/config/roboclaw_params.yaml

I updated the roboclaw_params.yaml file to include the correct default values for the recommended motors. I also added some comments explaining how the values are derived.

changed default values for gear_ratio and ticks_per_rev

---

scripts/roboclawtest.py

It seems that sometimes roboclaw.Open() will return a success even if it doesn't seem to be able to actually read any data from the roboclaw. I had this experience and one other person did in the Slack channel. I propose this code change so that we try both serial connections.

roboclawtest.py serial connections are not no longer mutually exclusive 

---

scripts/roboclawtest.py

Make the roboclawtest.py script more user friendly

---

ROS/osr_bringup/config/roboclaw_params.yaml

@igillespie I was racking my brain to figure out why my left back wheel was spinning super hard, even in duty mode. Small typo you [introduced in your last PR](https://github.com/nasa-jpl/osr-rover-code/commit/af230f92116c621f5dbe29d545e19fe9c62f3600). :) Since this is a hotfix with obvious consequences, I will merge this in right away.
@abust005

fix drive_left_back ticks_per_rev typo

---

setup/rpi.md

The Joystick is not read by the user by default since the input file does not have read permissions for other users. Adding the user to the Input group gives them read access to the joystick inputs.
closes #131

Add user to Input Group to enable joystick without changing permissions every time
